name: deepprecs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - scipy=1.7.3
  - cudatoolkit=11.3
  - scikit-learn
  - pandas
  - pylops
  - matplotlib
  - ipython
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - numpydoc
  - tqdm 
  - pip:
    - cupy-cuda113
    - pylops-gpu==0.0.1
    - torchsummary
    - torchviz
    - pytorch-msssim
    - pytorch-lightning
